development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: starter_kit_production
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
